// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: receiver.proto

package proto

import (
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_receiver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receiver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_receiver_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NatsConnected bool                   `protobuf:"varint,1,opt,name=nats_connected,json=natsConnected,proto3" json:"nats_connected,omitempty"`
	Ports         []*PortStatus          `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_receiver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receiver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_receiver_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetNatsConnected() bool {
	if x != nil {
		return x.NatsConnected
	}
	return false
}

func (x *GetStatusResponse) GetPorts() []*PortStatus {
	if x != nil {
		return x.Ports
	}
	return nil
}

type PortStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	IsOpen        bool                   `protobuf:"varint,3,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortStatus) Reset() {
	*x = PortStatus{}
	mi := &file_receiver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortStatus) ProtoMessage() {}

func (x *PortStatus) ProtoReflect() protoreflect.Message {
	mi := &file_receiver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortStatus.ProtoReflect.Descriptor instead.
func (*PortStatus) Descriptor() ([]byte, []int) {
	return file_receiver_proto_rawDescGZIP(), []int{2}
}

func (x *PortStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PortStatus) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortStatus) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

type GetClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolName  string                 `protobuf:"bytes,1,opt,name=protocol_name,json=protocolName,proto3" json:"protocol_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientsRequest) Reset() {
	*x = GetClientsRequest{}
	mi := &file_receiver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientsRequest) ProtoMessage() {}

func (x *GetClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receiver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientsRequest.ProtoReflect.Descriptor instead.
func (*GetClientsRequest) Descriptor() ([]byte, []int) {
	return file_receiver_proto_rawDescGZIP(), []int{3}
}

func (x *GetClientsRequest) GetProtocolName() string {
	if x != nil {
		return x.ProtocolName
	}
	return ""
}

type ClientInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ConnectedSince int64                  `protobuf:"varint,3,opt,name=connected_since,json=connectedSince,proto3" json:"connected_since,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_receiver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_receiver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_receiver_proto_rawDescGZIP(), []int{4}
}

func (x *ClientInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClientInfo) GetConnectedSince() int64 {
	if x != nil {
		return x.ConnectedSince
	}
	return 0
}

type GetClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*ClientInfo          `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientsResponse) Reset() {
	*x = GetClientsResponse{}
	mi := &file_receiver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientsResponse) ProtoMessage() {}

func (x *GetClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receiver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientsResponse.ProtoReflect.Descriptor instead.
func (*GetClientsResponse) Descriptor() ([]byte, []int) {
	return file_receiver_proto_rawDescGZIP(), []int{5}
}

func (x *GetClientsResponse) GetClients() []*ClientInfo {
	if x != nil {
		return x.Clients
	}
	return nil
}

type DisconnectClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolName  string                 `protobuf:"bytes,1,opt,name=protocol_name,json=protocolName,proto3" json:"protocol_name,omitempty"`
	ClientAddress string                 `protobuf:"bytes,2,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectClientRequest) Reset() {
	*x = DisconnectClientRequest{}
	mi := &file_receiver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectClientRequest) ProtoMessage() {}

func (x *DisconnectClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receiver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectClientRequest.ProtoReflect.Descriptor instead.
func (*DisconnectClientRequest) Descriptor() ([]byte, []int) {
	return file_receiver_proto_rawDescGZIP(), []int{6}
}

func (x *DisconnectClientRequest) GetProtocolName() string {
	if x != nil {
		return x.ProtocolName
	}
	return ""
}

func (x *DisconnectClientRequest) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

type DisconnectClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectClientResponse) Reset() {
	*x = DisconnectClientResponse{}
	mi := &file_receiver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectClientResponse) ProtoMessage() {}

func (x *DisconnectClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receiver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectClientResponse.ProtoReflect.Descriptor instead.
func (*DisconnectClientResponse) Descriptor() ([]byte, []int) {
	return file_receiver_proto_rawDescGZIP(), []int{7}
}

func (x *DisconnectClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_receiver_proto protoreflect.FileDescriptor

const file_receiver_proto_rawDesc = "" +
	"\n" +
	"\x0ereceiver.proto\x12\x05proto\x1a\rservice.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x12\n" +
	"\x10GetStatusRequest\"c\n" +
	"\x11GetStatusResponse\x12%\n" +
	"\x0enats_connected\x18\x01 \x01(\bR\rnatsConnected\x12'\n" +
	"\x05ports\x18\x02 \x03(\v2\x11.proto.PortStatusR\x05ports\"M\n" +
	"\n" +
	"PortStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x17\n" +
	"\ais_open\x18\x03 \x01(\bR\x06isOpen\"8\n" +
	"\x11GetClientsRequest\x12#\n" +
	"\rprotocol_name\x18\x01 \x01(\tR\fprotocolName\"_\n" +
	"\n" +
	"ClientInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12'\n" +
	"\x0fconnected_since\x18\x03 \x01(\x03R\x0econnectedSince\"A\n" +
	"\x12GetClientsResponse\x12+\n" +
	"\aclients\x18\x01 \x03(\v2\x11.proto.ClientInfoR\aclients\"e\n" +
	"\x17DisconnectClientRequest\x12#\n" +
	"\rprotocol_name\x18\x01 \x01(\tR\fprotocolName\x12%\n" +
	"\x0eclient_address\x18\x02 \x01(\tR\rclientAddress\"4\n" +
	"\x18DisconnectClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8c\x03\n" +
	"\x0fReceiverControl\x12D\n" +
	"\vSetLogLevel\x12\x19.proto.SetLogLevelRequest\x1a\x1a.proto.SetLogLevelResponse\x12>\n" +
	"\tGetStatus\x12\x17.proto.GetStatusRequest\x1a\x18.proto.GetStatusResponse\x12R\n" +
	"\x19GetActiveConnectionsCount\x12\x18.proto.GetClientsRequest\x1a\x1b.google.protobuf.Int32Value\x12J\n" +
	"\x13GetConnectedClients\x12\x18.proto.GetClientsRequest\x1a\x19.proto.GetClientsResponse\x12S\n" +
	"\x10DisconnectClient\x12\x1e.proto.DisconnectClientRequest\x1a\x1f.proto.DisconnectClientResponseB\x18Z\x16NavControlSystem/protob\x06proto3"

var (
	file_receiver_proto_rawDescOnce sync.Once
	file_receiver_proto_rawDescData []byte
)

func file_receiver_proto_rawDescGZIP() []byte {
	file_receiver_proto_rawDescOnce.Do(func() {
		file_receiver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_receiver_proto_rawDesc), len(file_receiver_proto_rawDesc)))
	})
	return file_receiver_proto_rawDescData
}

var file_receiver_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_receiver_proto_goTypes = []any{
	(*GetStatusRequest)(nil),         // 0: proto.GetStatusRequest
	(*GetStatusResponse)(nil),        // 1: proto.GetStatusResponse
	(*PortStatus)(nil),               // 2: proto.PortStatus
	(*GetClientsRequest)(nil),        // 3: proto.GetClientsRequest
	(*ClientInfo)(nil),               // 4: proto.ClientInfo
	(*GetClientsResponse)(nil),       // 5: proto.GetClientsResponse
	(*DisconnectClientRequest)(nil),  // 6: proto.DisconnectClientRequest
	(*DisconnectClientResponse)(nil), // 7: proto.DisconnectClientResponse
	(*SetLogLevelRequest)(nil),       // 8: proto.SetLogLevelRequest
	(*SetLogLevelResponse)(nil),      // 9: proto.SetLogLevelResponse
	(*wrappers.Int32Value)(nil),      // 10: google.protobuf.Int32Value
}
var file_receiver_proto_depIdxs = []int32{
	2,  // 0: proto.GetStatusResponse.ports:type_name -> proto.PortStatus
	4,  // 1: proto.GetClientsResponse.clients:type_name -> proto.ClientInfo
	8,  // 2: proto.ReceiverControl.SetLogLevel:input_type -> proto.SetLogLevelRequest
	0,  // 3: proto.ReceiverControl.GetStatus:input_type -> proto.GetStatusRequest
	3,  // 4: proto.ReceiverControl.GetActiveConnectionsCount:input_type -> proto.GetClientsRequest
	3,  // 5: proto.ReceiverControl.GetConnectedClients:input_type -> proto.GetClientsRequest
	6,  // 6: proto.ReceiverControl.DisconnectClient:input_type -> proto.DisconnectClientRequest
	9,  // 7: proto.ReceiverControl.SetLogLevel:output_type -> proto.SetLogLevelResponse
	1,  // 8: proto.ReceiverControl.GetStatus:output_type -> proto.GetStatusResponse
	10, // 9: proto.ReceiverControl.GetActiveConnectionsCount:output_type -> google.protobuf.Int32Value
	5,  // 10: proto.ReceiverControl.GetConnectedClients:output_type -> proto.GetClientsResponse
	7,  // 11: proto.ReceiverControl.DisconnectClient:output_type -> proto.DisconnectClientResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_receiver_proto_init() }
func file_receiver_proto_init() {
	if File_receiver_proto != nil {
		return
	}
	file_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_receiver_proto_rawDesc), len(file_receiver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_receiver_proto_goTypes,
		DependencyIndexes: file_receiver_proto_depIdxs,
		MessageInfos:      file_receiver_proto_msgTypes,
	}.Build()
	File_receiver_proto = out.File
	file_receiver_proto_goTypes = nil
	file_receiver_proto_depIdxs = nil
}
