grpc_port = 50051
monitoring_port = 9091
nats_url = ""

[log]
  log_level = "info"
  log_file_path = "./logs/receiver.log"
  max_size = 100
  max_backups = 5
  max_age = 30
  compress = true

[[ports]]
  port_number = 8002
  protocol = "ARNAVI"
  nats_topic = "nav.data.raw.arnavi"
  is_active = true
